name: Unit Test For NFTs
on: [push, pull_request]

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    env:
      REPORT_GAS: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm install --save-dev hardhat
      - run: npx hardhat compile
      - name: runtests
        run: npx hardhat --network hardhat test



