name: Unit Test For NFTs
on: [push, pull_request]

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    env:
      REPORT_GAS: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm install --save-dev hardhat
      - run: npx hardhat compile
      - name: Test
        run: npx hardhat test
      - name: Coverage
        run: npx hardhat coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: CodeChecks
        run: npx codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
